name: Build

on:
  pull_request:
    paths-ignore:
      - '.txt'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main
      - develop
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - 'LICENSE'
      - 'docs/**'

jobs:
  pr-build:
    if: >
      github.event_name == 'pull_request' && !github.event.pull_request.draft && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize' 
      )
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

  build:
    if: github.repository == 'WebGoat/WebGoat' && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: "Branch build"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-m2-

  sonarqube:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: SonarQube Analysis
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # Uncomment the lines below to fail the job if the Quality Gate fails
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
